name: API CI
#on: [push]
on:
  push:
    paths:
      - "./api/**"
      - ".github/workflows/api-ci.yml"


default:
  run:
    working-directory: ./api

jobs:
  unite-test:
    run-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Nodejs
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'npm'
          cache-dependecy-path: ./api/package-lock.json
        - name: install
          shell: powershell
          run: npm ci
        - name: run unit test
          shell: powershell
          run: npm run test
